---
# Deploy systems for Ansible Tower lab env
- name: Assign UUID to demo deployment
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Verify that we have the correct vault password
    ansible.builtin.debug:
      msg: "{{ vault_pw_test }}"

  - name: Generate UUID
    ansible.builtin.shell:
      uuidgen | cut -b 1,2,3,4
    register: uuid_output

  - name: Set UUID fact
    ansible.builtin.set_fact:
      uuid: "{{ uuid_output.stdout }}"
 
  - name: Print UUID
    ansible.builtin.debug:
      msg: "New lab environment UUID = {{ uuid }}"
  tags: always

- name: Provision lab systems on AWS EC2
  hosts: localhost
  gather_facts: false
  vars:
    count: "{{ lab_systems[system_type].count }}"
    host_prefix: "{{ lab_systems[system_type].hostprefix }}"
    image: "{{ lab_systems[system_type].image }}"
    instance_type: "{{ lab_systems[system_type].instance_type }}"
    volumes: "{{ lab_systems[system_type]['volumes'] }}"
  tasks:
  - name: Upload SSH public key to AWS EC2
    ansible.builtin.include_role:
      name: ssh-key-ec2
    tags: always

  - name: Provision RHEL 8 Tower systems
    vars:
      system_type: "rhel8_tower"
    ansible.builtin.include_role:
      name: deploy-rhel-ec2-instance
    tags: rhel8_tower

  - name: Provision RHEL 8 lab systems
    vars:
      system_type: "rhel8_client"
    ansible.builtin.include_role:
      name: deploy-rhel-ec2-instance
    tags: rhel8_client

  - name: Provision Windows 2019 lab systems
    vars:
      system_type: "win2019_client"
    ansible.builtin.include_role:
      name: deploy-windows-ec2-instance
    tags: win2019

  - name: Remove SSH public key from AWS EC2
    vars:
      remove_aws_key: true
    ansible.builtin.include_role:
      name: ssh-key-ec2
    tags: always

- name: Configure RHEL lab systems
  gather_facts: false
  hosts: launched_rhel_instances
  tasks:
  - name: Wait for host to start
    ansible.builtin.wait_for_connection:
      connect_timeout: 20
      sleep: 5
      timeout: 600

  - name: Add RHEL local accounts
    ansible.builtin.include_role:
      name: rhel-local-accounts

  - name: Configure RHEL ec2 instances
    ansible.builtin.include_role:
      name: config-rhel-ec2-instance
  tags: rhel8_client, rhel8_tower

- name: Configure Windows lab systems
  gather_facts: false
  hosts: launched_windows_instances
  tasks:
  - name: Wait for host to start
    ansible.builtin.wait_for_connection:
      connect_timeout: 20
      sleep: 5
      timeout: 600

  - name: Add Windows local accounts
    ansible.builtin.include_role:
      name: win-local-accounts

  - name: Configure Windows ec2 instances
    ansible.builtin.include_role:
      name: config-windows-ec2-instance
  tags: win2019

- name: Communicate deployment info
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Print UUID
    ansible.builtin.debug:
      msg: "Your lab UUID is {{ uuid }}."
  tags: always

- name: Communicate RHEL lab system info
  hosts: launched_rhel_instances
  gather_facts: false
  tasks:
  - name: Print lab info - RHEL systtems
    ansible.builtin.include_role:
      name: lab-info
  tags: rhel8_client, rhel8_tower

- name: Communicate Windows lab system info
  hosts: launched_windows_instances
  gather_facts: false
  tasks:
  - name: Print lab info - Windows systems
    ansible.builtin.include_role:
      name: lab-info
  tags: win2019
