---
# remove_lab_environment.yml
- name: Remove EC2 instances
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Call destroy-ec2-instances role
    ansible.builtin.include_role:
      name: destroy-ec2-instances 
