---
# Deploy systems for Ansible Tower lab env
- name: Assign UUID to demo deployment
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Generate UUID
    ansible.builtin.shell:
      uuidgen | cut -b 1,2,3,4
    register: uuid_output

  - name: Set UUID fact
    ansible.builtin.set_fact:
      uuid: "{{ uuid_output.stdout }}"
  tags: always

- name: debug
  hosts: localhost
  gather_facts: false
  vars_files:
  - group_vars/launched_windows_instances/main.yml
  tasks:
  - name: print debug 1
    ansible.builtin.debug:
      msg: "The UUID is {{ uuid }}"
  - name: print debug 2
    ansible.builtin.debug:
      msg: "ansible_password is {{ ansible_password }}"
