---
# tasks file for win-local-accounts
- name: Configure local accounts
  block:
  - name: Add local user
    win_user:
      name: "{{ username }}"
      password: "{{ password }}"
      description: "{{ description }}"
      fullname: "{{ fullname }}"
      password_never_expires: "{{ password_never_expires }}"
      state: present

  - name: Add user to local Administrators group
    win_group_membership:
      name: Administrators
      members:
      - "{{ username }}"
      state: present

  - name: Add user to local Remote Desktop Users group
    win_group_membership:
      name: Remote Desktop Users
      members:
      - "{{ username }}"
      state: present
