---
# tasks file for ssh-key-ec2
- name: Create AWS deployment key
  block:
  - name: Create directory for SSH key
    ansible.builtin.file:
      path: "{{ ssh_key_dir }}"
      state: directory
      mode: '0700'

  - name: Generate SSH key for local user
    community.crypto.openssh_keypair:
      path: "{{ my_keyfile }}"

  - name: Upload public key to AWS
    amazon.aws.ec2_key:
      name: "{{ my_keyname }}"
      key_material: "{{ lookup('file', '{{ my_public_key }}') }}"
      region: "{{ region }}"
      state: present
  when: not remove_aws_key

- name: Cleanup AWS deployment key
  amazon.aws.ec2_key:
    name: "{{ my_keyname }}"
    region: "{{ region }}"
    state: absent
  when: remove_aws_key

